"""link_sources_to_incidents

Revision ID: 66e55b4fc444
Revises: b23ad8a0f2d7
Create Date: 2026-04-18 14:40:41.563358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '66e55b4fc444'
down_revision: Union[str, None] = 'b23ad8a0f2d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('access_events', sa.Column('incident_id', sa.UUID(), nullable=True))
    op.alter_column('access_events', 'failure_reason',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=256),
               existing_nullable=True)
    op.create_foreign_key(None, 'access_events', 'incidents', ['incident_id'], ['id'])
    op.add_column('drone_telemetry', sa.Column('heading', sa.Integer(), nullable=True))
    op.add_column('drone_telemetry', sa.Column('incident_id', sa.UUID(), nullable=True))
    op.alter_column('drone_telemetry', 'mission_id',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('drone_telemetry', 'mission_type',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('drone_telemetry', 'drone_id',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('drone_telemetry', 'lat',
               existing_type=sa.NUMERIC(precision=10, scale=7),
               nullable=True)
    op.alter_column('drone_telemetry', 'lon',
               existing_type=sa.NUMERIC(precision=10, scale=7),
               nullable=True)
    op.alter_column('drone_telemetry', 'altitude_m',
               existing_type=sa.NUMERIC(precision=8, scale=2),
               type_=sa.Numeric(precision=6, scale=2),
               existing_nullable=True)
    op.alter_column('drone_telemetry', 'flagged',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('drone_telemetry', 'flag_reason',
               existing_type=sa.TEXT(),
               type_=sa.String(length=256),
               existing_nullable=True)
    op.create_foreign_key(None, 'drone_telemetry', 'incidents', ['incident_id'], ['id'])
    op.drop_column('drone_telemetry', 'heading_deg')
    op.add_column('sensor_readings', sa.Column('incident_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'sensor_readings', 'incidents', ['incident_id'], ['id'])
    op.add_column('vehicle_detections', sa.Column('incident_id', sa.UUID(), nullable=True))
    op.alter_column('vehicle_detections', 'lat',
               existing_type=sa.NUMERIC(precision=10, scale=7),
               nullable=True)
    op.alter_column('vehicle_detections', 'lon',
               existing_type=sa.NUMERIC(precision=10, scale=7),
               nullable=True)
    op.alter_column('vehicle_detections', 'speed_kmh',
               existing_type=sa.NUMERIC(precision=6, scale=2),
               type_=sa.Numeric(precision=5, scale=2),
               existing_nullable=True)
    op.alter_column('vehicle_detections', 'in_restricted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.create_foreign_key(None, 'vehicle_detections', 'incidents', ['incident_id'], ['id'])
    op.drop_column('vehicle_detections', 'heading_deg')
    op.add_column('weather_readings', sa.Column('incident_id', sa.UUID(), nullable=True))
    op.add_column('weather_readings', sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('weather_readings', 'temp_c',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Numeric(precision=4, scale=1),
               existing_nullable=True)
    op.alter_column('weather_readings', 'wind_kmh',
               existing_type=sa.NUMERIC(precision=6, scale=2),
               type_=sa.Numeric(precision=5, scale=2),
               existing_nullable=True)
    op.alter_column('weather_readings', 'gust_kmh',
               existing_type=sa.NUMERIC(precision=6, scale=2),
               type_=sa.Numeric(precision=5, scale=2),
               existing_nullable=True)
    op.alter_column('weather_readings', 'precipitation',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.create_foreign_key(None, 'weather_readings', 'incidents', ['incident_id'], ['id'])
    op.drop_column('weather_readings', 'pressure_hpa')
    op.drop_column('weather_readings', 'wind_direction')
    op.drop_column('weather_readings', 'humidity_pct')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weather_readings', sa.Column('humidity_pct', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True))
    op.add_column('weather_readings', sa.Column('wind_direction', sa.VARCHAR(length=16), autoincrement=False, nullable=True))
    op.add_column('weather_readings', sa.Column('pressure_hpa', sa.NUMERIC(precision=8, scale=2), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'weather_readings', type_='foreignkey')
    op.alter_column('weather_readings', 'precipitation',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=32),
               existing_nullable=True)
    op.alter_column('weather_readings', 'gust_kmh',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.NUMERIC(precision=6, scale=2),
               existing_nullable=True)
    op.alter_column('weather_readings', 'wind_kmh',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.NUMERIC(precision=6, scale=2),
               existing_nullable=True)
    op.alter_column('weather_readings', 'temp_c',
               existing_type=sa.Numeric(precision=4, scale=1),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=True)
    op.drop_column('weather_readings', 'metadata_json')
    op.drop_column('weather_readings', 'incident_id')
    op.add_column('vehicle_detections', sa.Column('heading_deg', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'vehicle_detections', type_='foreignkey')
    op.alter_column('vehicle_detections', 'in_restricted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('vehicle_detections', 'speed_kmh',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.NUMERIC(precision=6, scale=2),
               existing_nullable=True)
    op.alter_column('vehicle_detections', 'lon',
               existing_type=sa.NUMERIC(precision=10, scale=7),
               nullable=False)
    op.alter_column('vehicle_detections', 'lat',
               existing_type=sa.NUMERIC(precision=10, scale=7),
               nullable=False)
    op.drop_column('vehicle_detections', 'incident_id')
    op.drop_constraint(None, 'sensor_readings', type_='foreignkey')
    op.drop_column('sensor_readings', 'incident_id')
    op.add_column('drone_telemetry', sa.Column('heading_deg', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'drone_telemetry', type_='foreignkey')
    op.alter_column('drone_telemetry', 'flag_reason',
               existing_type=sa.String(length=256),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('drone_telemetry', 'flagged',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('drone_telemetry', 'altitude_m',
               existing_type=sa.Numeric(precision=6, scale=2),
               type_=sa.NUMERIC(precision=8, scale=2),
               existing_nullable=True)
    op.alter_column('drone_telemetry', 'lon',
               existing_type=sa.NUMERIC(precision=10, scale=7),
               nullable=False)
    op.alter_column('drone_telemetry', 'lat',
               existing_type=sa.NUMERIC(precision=10, scale=7),
               nullable=False)
    op.alter_column('drone_telemetry', 'drone_id',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('drone_telemetry', 'mission_type',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('drone_telemetry', 'mission_id',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.drop_column('drone_telemetry', 'incident_id')
    op.drop_column('drone_telemetry', 'heading')
    op.drop_constraint(None, 'access_events', type_='foreignkey')
    op.alter_column('access_events', 'failure_reason',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)
    op.drop_column('access_events', 'incident_id')
    # ### end Alembic commands ###
