"""add_site_id_to_incident

Revision ID: b23ad8a0f2d7
Revises: bfc19baaa1d2
Create Date: 2026-04-18 14:39:04.713217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b23ad8a0f2d7'
down_revision: Union[str, None] = 'bfc19baaa1d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidents', sa.Column('site_id', sa.String(length=64), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incidents', 'site_id')
    # ### end Alembic commands ###
