"""initial_forensic_schema

Revision ID: bfc19baaa1d2
Revises: 
Create Date: 2026-04-18 14:10:46.943509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bfc19baaa1d2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('site_id', sa.String(length=64), nullable=False),
    sa.Column('gate_id', sa.String(length=128), nullable=False),
    sa.Column('zone', sa.String(length=64), nullable=False),
    sa.Column('badge_id', sa.String(length=128), nullable=True),
    sa.Column('person_id', sa.String(length=128), nullable=True),
    sa.Column('outcome', sa.String(length=32), nullable=False),
    sa.Column('failure_reason', sa.String(length=128), nullable=True),
    sa.Column('lat', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('lon', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('briefings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('briefing_date', sa.Date(), nullable=False),
    sa.Column('site_id', sa.String(length=64), nullable=False),
    sa.Column('q1_summary', sa.Text(), nullable=True),
    sa.Column('q2_harmless', sa.Text(), nullable=True),
    sa.Column('q3_escalations', sa.Text(), nullable=True),
    sa.Column('q4_drone_ops', sa.Text(), nullable=True),
    sa.Column('q5_follow_ups', sa.Text(), nullable=True),
    sa.Column('export_text', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drone_telemetry',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('site_id', sa.String(length=64), nullable=False),
    sa.Column('mission_id', sa.String(length=128), nullable=False),
    sa.Column('mission_type', sa.String(length=64), nullable=False),
    sa.Column('drone_id', sa.String(length=128), nullable=False),
    sa.Column('lat', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('lon', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('altitude_m', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('heading_deg', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('waypoint_index', sa.Integer(), nullable=True),
    sa.Column('observation', sa.Text(), nullable=True),
    sa.Column('flagged', sa.Boolean(), nullable=False),
    sa.Column('flag_reason', sa.Text(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('investigation_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('site_id', sa.String(length=64), nullable=False),
    sa.Column('trigger_type', sa.String(length=64), nullable=False),
    sa.Column('trigger_source', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('events_fetched', sa.Integer(), nullable=True),
    sa.Column('clusters_found', sa.Integer(), nullable=True),
    sa.Column('incidents_created', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sensor_readings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('site_id', sa.String(length=64), nullable=False),
    sa.Column('zone', sa.String(length=64), nullable=False),
    sa.Column('sensor_id', sa.String(length=128), nullable=False),
    sa.Column('sensor_type', sa.String(length=64), nullable=False),
    sa.Column('raw_value', sa.Numeric(), nullable=True),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('threshold', sa.Numeric(), nullable=True),
    sa.Column('threshold_breached', sa.Boolean(), nullable=False),
    sa.Column('lat', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('lon', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shift_schedule',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('site_id', sa.String(length=64), nullable=False),
    sa.Column('shift_date', sa.Date(), nullable=False),
    sa.Column('shift_type', sa.String(length=32), nullable=False),
    sa.Column('shift_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('shift_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('supervisor_id', sa.String(length=128), nullable=True),
    sa.Column('headcount', sa.Integer(), nullable=True),
    sa.Column('active_zones', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('scheduled_maintenance', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('site_zones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('site_id', sa.String(length=64), nullable=False),
    sa.Column('zone_id', sa.String(length=128), nullable=False),
    sa.Column('zone_name', sa.String(length=256), nullable=True),
    sa.Column('zone_type', sa.String(length=64), nullable=True),
    sa.Column('is_restricted', sa.Boolean(), nullable=False),
    sa.Column('access_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('boundary_geojson', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('expected_vehicles', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('zone_id')
    )
    op.create_table('vehicle_detections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('site_id', sa.String(length=64), nullable=False),
    sa.Column('zone', sa.String(length=64), nullable=False),
    sa.Column('vehicle_id', sa.String(length=128), nullable=True),
    sa.Column('vehicle_type', sa.String(length=64), nullable=True),
    sa.Column('lat', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('lon', sa.Numeric(precision=10, scale=7), nullable=False),
    sa.Column('speed_kmh', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('heading_deg', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('in_restricted', sa.Boolean(), nullable=False),
    sa.Column('path_segment_id', sa.String(length=128), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weather_readings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('site_id', sa.String(length=64), nullable=False),
    sa.Column('wind_kmh', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('wind_direction', sa.String(length=16), nullable=True),
    sa.Column('gust_kmh', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('temp_c', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('humidity_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('visibility_m', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('precipitation', sa.String(length=32), nullable=True),
    sa.Column('pressure_hpa', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('incidents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('investigation_run_id', sa.UUID(), nullable=True),
    sa.Column('related_event_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('related_sources', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('cluster_centroid_lat', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('cluster_centroid_lon', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('hypothesis', sa.Text(), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('confidence_level', sa.String(length=16), nullable=False),
    sa.Column('confidence_rationale', sa.Text(), nullable=True),
    sa.Column('recommended_action', sa.String(length=64), nullable=False),
    sa.Column('reasoning_trace', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tool_calls_made', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('triggered_by', sa.String(length=64), nullable=True),
    sa.Column('review_status', sa.String(length=32), nullable=True),
    sa.Column('human_note', sa.Text(), nullable=True),
    sa.Column('original_confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.ForeignKeyConstraint(['investigation_run_id'], ['investigation_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drone_missions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('incident_id', sa.UUID(), nullable=True),
    sa.Column('mission_status', sa.String(length=32), nullable=True),
    sa.Column('path_geojson', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('waypoints', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('findings', sa.Text(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hook_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('site_id', sa.String(length=64), nullable=False),
    sa.Column('submitted_by', sa.String(length=128), nullable=False),
    sa.Column('observation', sa.Text(), nullable=False),
    sa.Column('zone', sa.String(length=64), nullable=True),
    sa.Column('lat', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('lon', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('severity_hint', sa.String(length=16), nullable=True),
    sa.Column('lookback_minutes', sa.Integer(), nullable=False),
    sa.Column('include_sources', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=True),
    sa.Column('incident_id', sa.UUID(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['investigation_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('ix_events_event_type', table_name='events')
    op.drop_index('ix_events_incident_id', table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('event_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('lat', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('lon', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('metadata_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('incident_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='events_pkey')
    )
    op.create_index('ix_events_incident_id', 'events', ['incident_id'], unique=False)
    op.create_index('ix_events_event_type', 'events', ['event_type'], unique=False)
    op.drop_table('hook_events')
    op.drop_table('drone_missions')
    op.drop_table('incidents')
    op.drop_table('weather_readings')
    op.drop_table('vehicle_detections')
    op.drop_table('site_zones')
    op.drop_table('shift_schedule')
    op.drop_table('sensor_readings')
    op.drop_table('investigation_runs')
    op.drop_table('drone_telemetry')
    op.drop_table('briefings')
    op.drop_table('access_events')
    # ### end Alembic commands ###
